### ISSUE TITLE
[ILLA App Idea]  Json to CSV Converter

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2699] opened 2023-10-12 11:28 UTC
**Is your feature request related to a problem? Please describe.** 
Create a JSON to CSV Converter.

**Comment by AkshitMital** [comment] 2023-10-13 20:19
#2769 Created a JSON to CSV Converter using ILLA AI

**Comment by seharbat00l** [comment] 2023-10-14 10:41
I want to contribute. Can you assign this to me?

**Comment by AruSeito** [comment] 2023-10-14 12:11
@seharbat00l Hello,someone has already made the PR

**Comment by giriprasathd** [comment] 2023-10-20 12:18
@donqu1xotechina  can you assign me?

**Comment by shivanshu814** [comment] 2023-10-21 10:57
@AruSeito can you please assign me this i have finished this i have to make pr only

**Comment by sharsha315** [comment] 2023-10-23 15:29
Hi @donqu1xotechina, if the issue is not assigned and still open, can I have the opportunity to work on this issue.

**Closed** 2023-11-13 03:44 UTC
Labels: build with ILLA, hacktoberfest
